---
title: "Project 1 Blog Post"
author: "Jordan Tanley"
date: "6/23/2022"
---


```{r, echo=FALSE}
library(knitr)
knitr::opts_chunk$set(fig.path = "../images/")
```


## 3rd Blog: Reflection of Project 1


This project required me to learn how to access and pull data from an API and write functions to translate the data into usable and customizable data sets. I chose to examine the [Pokemon](https://pokeapi.co/). I created a function to access characteristics of 10 different pokemon separately. I then created another function to basically rbind the individual rows created by the previous function. This way there's one row for each pokemon. Then, I added a new variable, `size`, based on the weight class. This allowed for an extra dimension for analysis. Finally, I performed some numerical and graphical exploratory analyses. There were no exciting discoveries found in this process, but I'd imagine if I expanded to API accessing function to create a larger dataset, there might be more interesting findings. 


Honestly, I think the most difficult part of this process was learning how to access the API. I had no experience with APIs prior to our recent homework assignment, which didn't really give us much more information. Even now, after completing the project, I still don't feel comfortable that I really know what exactly I did and/or if I did it correctly. I'm sure there was a lot less painful way to accomplish the goals of this project, but with my limited knowledge on accessing APIs, I did the best I could. I think in the future, I'd like to do some deeper research into better ways to access APIs to be better prepared.

## Links

* [Github repo](https://github.com/jetanley/Jordans-Project-1)  
* [Project page](https://jetanley.github.io/Jordans-Project-1/)



