---
title: "5th Blog Post"
author: "Jordan Tanley"
date: '2022-07-19'
output: html_document
---

```{r, echo=FALSE}
library(knitr)
knitr::opts_chunk$set(fig.path = "../images/")
```


### What your current thoughts are in terms of using R for data science - do you think you'll continue to use R going forward?  Why or why not?

I've always loved using R. If I had a choice, I'd stick with using R in the future. Currently, my job (the full-time job I will have upon completing my Master's degree in a few weeks) requires me to use SAS for all of my work for at least the first year or two that I'm there. Who knows by then whether I'll want to switch back to R or if I'll stick with SAS. I'd like to think I'd switch to R... 

### What things are you going to do differently in practice now that you've had this course?

Piping! I had used it in the past but never understood it. Now I feel a ton more comfortable with it and will definitely be using it in the future. 

### What areas of statistics/data science are you thinking about exploring further?

Biostats! I'm super interested in exploring the many uses of statistics within biological research - especially within clinical trails. 
